package TestPackage;

public class TestProduct {
    public static void main(String[] args) {
        Product p1 = new Product(101,"KeyBoard",299);
        int arr[] = new int[5];
        Product p2 = new Product(201,"Pen",5);
        // We can override hashcode() method according to our need as did below.
        System.out.println("HashCode for p1 is : " + p1.hashCode());     //for every object hashcode is generated by JVM.Here overridden.
        System.out.println("HashCode for p1 is : " + p2.hashCode());     //for every object hashcode is generated by JVM.Here overridden.
        System.out.println("HashCode for arr is : " + arr.hashCode());     //for every object hashcode is generated by JVM.

        System.out.println("Printing Object " + p1); // if not overrided we will get something like "prod@42..."
        // override toString() method in Product Class for better showing product
        // After overriding toString in Product Class we get better display of object
        System.out.println("Printing Object in better way by overriding toString method " + p1); // No need to call toString even here because we have overrided object method


        // p1.equals(p2) will check for same reference
        // In string class it is overrriden so that we check for the same content using equals method
        // lets override equals object class in product  so that wer can check for actual content are equal or not
        System.out.println("Check if content of objects p1 and p2 are same or not : " + p1.equals(p2));

        //Clone Method of Object Class

        Product p3 = (Product) p1.clone();
        System.out.println("p3 after cloning p1 is  " + p3);
    }
}
